from Fkt_GUI_For_Fourier.Fkt_Get_Data.Calc_AV_Data import Calc_AV_Data
from Fkt_GUI_For_Fourier.Fkt_Get_Data.Calc_Fourierkoefficient import Calc_Fourierkoefficient
from Fkt_GUI_For_Fourier.Fkt_Get_Data.Calc_Points import Calc_Points
from Fkt_GUI_For_Fourier.Fkt_Get_Data.Change_Time_Format import Change_Time_Format
from Fkt_GUI_For_Fourier.Fkt_Get_Data.Form_Poly import Form_Poly
from Fkt_GUI_For_Fourier.Fkt_Get_Data.Number_Of_Values_In_Period import Number_Of_Values_In_Period