from Fkt_GUI_For_Fourier.Fkt_Get_Data.Fkt_Calc_Fourierkoefficient.Calc_Poly import Calc_Poly
from Fkt_GUI_For_Fourier.Fkt_Get_Data.Fkt_Calc_Fourierkoefficient.Integral_Poly import Integral_Poly
from Fkt_GUI_For_Fourier.Fkt_Get_Data.Fkt_Calc_Fourierkoefficient.Poly_For_Integral import Poly_For_Integral